FROM nginx:latest

RUN apt-get update && apt-get install -y curl vim
COPY reverse-proxy.conf /etc/nginx/conf.d/reverse-proxy.conf
# RUN ln -sf /dev/stdout /var/log/nginx/access.log \
#     && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 8020
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]
